/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppLoginIndexRouteImport } from './routes/_app/login/index'
import { Route as AppContactIndexRouteImport } from './routes/_app/contact/index'
import { Route as AppAboutIndexRouteImport } from './routes/_app/about/index'
import { Route as DashboardProjectsNewRouteImport } from './routes/dashboard/projects/new'
import { Route as DashboardProjectsEditRouteImport } from './routes/dashboard/projects/edit'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardProjectsUploadProjectidRouteImport } from './routes/dashboard/projects/upload.$projectid'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLoginIndexRoute = AppLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContactIndexRoute = AppContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAboutIndexRoute = AppAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => AppRouteRoute,
} as any)
const DashboardProjectsNewRoute = DashboardProjectsNewRouteImport.update({
  id: '/dashboard/projects/new',
  path: '/dashboard/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsEditRoute = DashboardProjectsEditRouteImport.update({
  id: '/dashboard/projects/edit',
  path: '/dashboard/projects/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsUploadProjectidRoute =
  DashboardProjectsUploadProjectidRouteImport.update({
    id: '/dashboard/projects/upload/$projectid',
    path: '/dashboard/projects/upload/$projectid',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/projects/edit': typeof DashboardProjectsEditRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/about': typeof AppAboutIndexRoute
  '/contact': typeof AppContactIndexRoute
  '/login': typeof AppLoginIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/dashboard/projects/upload/$projectid': typeof DashboardProjectsUploadProjectidRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/projects/edit': typeof DashboardProjectsEditRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/about': typeof AppAboutIndexRoute
  '/contact': typeof AppContactIndexRoute
  '/login': typeof AppLoginIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/dashboard/projects/upload/$projectid': typeof DashboardProjectsUploadProjectidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/projects/edit': typeof DashboardProjectsEditRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/_app/about/': typeof AppAboutIndexRoute
  '/_app/contact/': typeof AppContactIndexRoute
  '/_app/login/': typeof AppLoginIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/dashboard/projects/upload/$projectid': typeof DashboardProjectsUploadProjectidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard/projects/edit'
    | '/dashboard/projects/new'
    | '/about'
    | '/contact'
    | '/login'
    | '/projects'
    | '/dashboard/projects/upload/$projectid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard/projects/edit'
    | '/dashboard/projects/new'
    | '/about'
    | '/contact'
    | '/login'
    | '/projects'
    | '/dashboard/projects/upload/$projectid'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard/projects/edit'
    | '/dashboard/projects/new'
    | '/_app/about/'
    | '/_app/contact/'
    | '/_app/login/'
    | '/_app/projects/'
    | '/dashboard/projects/upload/$projectid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  DashboardProjectsEditRoute: typeof DashboardProjectsEditRoute
  DashboardProjectsNewRoute: typeof DashboardProjectsNewRoute
  DashboardProjectsUploadProjectidRoute: typeof DashboardProjectsUploadProjectidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/login/': {
      id: '/_app/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/contact/': {
      id: '/_app/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/about/': {
      id: '/_app/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/dashboard/projects/new': {
      id: '/dashboard/projects/new'
      path: '/dashboard/projects/new'
      fullPath: '/dashboard/projects/new'
      preLoaderRoute: typeof DashboardProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/projects/edit': {
      id: '/dashboard/projects/edit'
      path: '/dashboard/projects/edit'
      fullPath: '/dashboard/projects/edit'
      preLoaderRoute: typeof DashboardProjectsEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/projects/upload/$projectid': {
      id: '/dashboard/projects/upload/$projectid'
      path: '/dashboard/projects/upload/$projectid'
      fullPath: '/dashboard/projects/upload/$projectid'
      preLoaderRoute: typeof DashboardProjectsUploadProjectidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAboutIndexRoute: typeof AppAboutIndexRoute
  AppContactIndexRoute: typeof AppContactIndexRoute
  AppLoginIndexRoute: typeof AppLoginIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAboutIndexRoute: AppAboutIndexRoute,
  AppContactIndexRoute: AppContactIndexRoute,
  AppLoginIndexRoute: AppLoginIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  DashboardProjectsEditRoute: DashboardProjectsEditRoute,
  DashboardProjectsNewRoute: DashboardProjectsNewRoute,
  DashboardProjectsUploadProjectidRoute: DashboardProjectsUploadProjectidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
